# Copyright (C) 2024-2026 Tobias Rosenbaum
#
# This file is part of Applire.
#
# Applire is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Applire is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Applire. If not, see <https://www.gnu.org/licenses/>.

"""Segmented CV-tailoring prompts — outline-then-expand (ADR-047 §1 / E036 US189).

Each section is generated by its own small call so no single output needs a large
budget (ADR-047). All section prompts share the same truthfulness + output-language
discipline as the single-call SYSTEM_PROMPT (cv_tailoring.py rules 1/5/7/8) — scoped
to the section — so segmentation never weakens the no-fabrication or ADR-038 guarantees.

System-prompt role phrases are stable: services/cv.py and MockLLMProvider route on them
("cv outline planner", "cv work experience writer", "cv summary writer", "cv skills
writer", "cv education writer", "cv projects writer"). Do not rename without updating both.
"""

import json


def _language_name(output_language: str) -> str:
    return "GERMAN" if output_language == "de" else "ENGLISH"


def _ledger_section(keyword_ledger: list[dict] | None) -> str:
    """Render the shared Keyword Ledger prompt block (ADR-048 / US200) as a trailing
    section, or "" when there is no ledger. Imported lazily to avoid a prompts→services
    import at module load."""
    from applire.services.keyword_ledger import render_ledger_prompt_block

    block = render_ledger_prompt_block(keyword_ledger)
    return f"{block}\n\n" if block else ""


# Shared truthfulness + language discipline, injected into every section prompt.
_CORE_RULES = """\
- Do NOT add achievements, technologies, projects, metrics, or facts not explicitly present
  in the candidate material. Keep companies, roles, dates, degrees, and numbers EXACTLY as
  given. When in doubt, leave it out.
- Claim-strength: mirror the source's verb strength; never upgrade "supported"/"assisted" to
  "led"/"owned", never enlarge team sizes/budgets/magnitudes, never assign a more senior title.
- Output language: write ALL prose in the OUTPUT LANGUAGE stated in the user message,
  translating from the source where needed (translating is not inventing). Skill/discipline
  phrases are ordinary language and MUST be translated; only proper nouns (company/product/
  tool names, dates, metrics) stay unchanged."""


# ---------------------------------------------------------------------------
# Outline — the shared tailoring directive (small)
# ---------------------------------------------------------------------------

OUTLINE_SYSTEM_PROMPT = f"""\
You are a DACH cv outline planner. Given a job and a candidate profile, produce a SHORT
tailoring directive that later section writers will all follow — so the finished CV reads
with one consistent voice. Decide the summary angle, which skills to foreground, and a
one-line emphasis theme per work entry. Do NOT write the CV itself here.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{
  "role_order": [string],          // work-entry ids, most-relevant-first (advisory only)
  "summary_angle": string,          // the angle the summary should take
  "skills_focus": [string],         // skills to lead with, drawn from the profile
  "per_role_themes": {{string: string}}  // work-entry id -> one-line emphasis theme
}}"""


def build_outline_prompt(
    job_analysis: dict, profile: dict, output_language: str, keyword_ledger: list[dict] | None = None
) -> str:
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        "Return the tailoring directive JSON."
    )


# ---------------------------------------------------------------------------
# Per-work-entry section — tailored bullets + nested projects only
# ---------------------------------------------------------------------------

WORK_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv work experience writer. Rewrite the bullets for ONE work-history entry to
maximise relevance to the job, following the shared tailoring directive. You return ONLY the
tailored bullets and any nested projects — never the company, role, or dates (those are
carried verbatim from the profile by the system).

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{
  "bullets": [string],
  "projects": [{{"name": string, "bullets": [string]}}]
}}"""


def build_work_section_prompt(
    entry: dict,
    directive: dict,
    job_analysis: dict,
    keyword_gaps: list[str],
    output_language: str,
    keyword_ledger: list[dict] | None = None,
) -> str:
    theme = (directive.get("per_role_themes") or {}).get(entry.get("id"), "")
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"EMPHASIS THEME FOR THIS ENTRY: {theme or '(use the summary angle)'}\n"
        f"SUMMARY ANGLE: {directive.get('summary_angle', '')}\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"THIS WORK ENTRY:\n{json.dumps(entry, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        f"KEYWORD GAPS (use only where explicitly supported by this entry):\n"
        f"{json.dumps(keyword_gaps, ensure_ascii=False)}\n\n"
        "Return the tailored bullets + nested projects JSON for this entry only."
    )


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

SUMMARY_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv summary writer. Write a concise professional summary (2–3 sentences, third
person) tailored to the job, taking the angle from the shared directive.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown: {{"summary": string}}"""


def build_summary_prompt(
    directive: dict, job_analysis: dict, profile: dict, critical_gaps: list[str], output_language: str
) -> str:
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"SUMMARY ANGLE: {directive.get('summary_angle', '')}\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        f"CRITICAL GAPS (acknowledge if applicable):\n{json.dumps(critical_gaps, ensure_ascii=False)}\n\n"
        "Return the summary JSON."
    )


# ---------------------------------------------------------------------------
# Skills
# ---------------------------------------------------------------------------

SKILLS_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv skills writer. Filter and order the candidate's skills to lead with those
the job requires, following the directive's skills focus. Include a keyword-gap skill ONLY if
the profile explicitly demonstrates it.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown: {{"skills": [string]}}"""


def build_skills_prompt(
    directive: dict,
    job_analysis: dict,
    profile: dict,
    keyword_gaps: list[str],
    output_language: str,
    keyword_ledger: list[dict] | None = None,
) -> str:
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"SKILLS TO FOREGROUND: {json.dumps(directive.get('skills_focus') or [], ensure_ascii=False)}\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        f"KEYWORD GAPS (include only where explicitly demonstrated):\n"
        f"{json.dumps(keyword_gaps, ensure_ascii=False)}\n\n"
        "Return the skills JSON."
    )


# ---------------------------------------------------------------------------
# Education + languages
# ---------------------------------------------------------------------------

EDUCATION_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv education writer. Return the candidate's education entries and spoken
languages, kept factually exact. Translate field/degree labels into the output language;
keep institution names and dates unchanged.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{
  "education": [{{"institution": string, "degree": string, "field": string,
                 "start_date": string, "end_date": string or null}}],
  "languages": [{{"language": string, "level": string}}]
}}"""


def build_education_prompt(profile: dict, output_language: str) -> str:
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        "Return the education + languages JSON."
    )


# ---------------------------------------------------------------------------
# Standalone projects (those with no work/volunteer parent — US187)
# ---------------------------------------------------------------------------

PROJECTS_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv projects writer. Return ONLY standalone projects (those not tied to a work
or volunteer position), tailored to the job. If the profile has none, return an empty list.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{"projects": [{{"name": string, "bullets": [string]}}]}}"""


def build_projects_prompt(
    directive: dict, job_analysis: dict, profile: dict, output_language: str
) -> str:
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        "Return the standalone-projects JSON."
    )
