# Copyright (C) 2024-2026 Tobias Rosenbaum
#
# This file is part of Applire.
#
# Applire is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Applire is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Applire. If not, see <https://www.gnu.org/licenses/>.

"""Segmented CV-tailoring prompts — outline-then-expand (ADR-047 §1 / E036 US189).

Each section is generated by its own small call so no single output needs a large
budget (ADR-047). All section prompts share the same truthfulness + output-language
discipline as the single-call SYSTEM_PROMPT (cv_tailoring.py, ADR-067 prose-craft
brief) — scoped to the section — so segmentation never weakens the no-fabrication or
ADR-038 guarantees. Education/languages have no section call (ADR-067 clause 3:
transcription is copied from the vault at assembly, never routed through an LLM).

System-prompt role phrases are stable: services/cv.py and MockLLMProvider route on them
("cv outline planner", "cv work experience writer", "cv summary writer", "cv skills
writer", "cv projects writer"). Do not rename without updating both.
"""

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from applire.services.cv_budget import BudgetResult


def _language_name(output_language: str) -> str:
    return "GERMAN" if output_language == "de" else "ENGLISH"


def _ledger_section(keyword_ledger: list[dict] | None) -> str:
    """Render the shared Keyword Ledger prompt block (ADR-048 / US200) as a trailing
    section, or "" when there is no ledger. Imported lazily to avoid a prompts→services
    import at module load."""
    from applire.services.keyword_ledger import render_ledger_prompt_block

    block = render_ledger_prompt_block(keyword_ledger)
    return f"{block}\n\n" if block else ""


# Shared truthfulness + language discipline, injected into every section prompt.
_CORE_RULES = """\
- Do NOT add achievements, technologies, projects, metrics, or facts not explicitly present
  in the candidate material. Keep companies, roles, dates, degrees, and numbers EXACTLY as
  given. When in doubt, leave it out.
- Grounding is PER ENTRY (ADR-071): a bullet under a work entry must trace to THAT ENTRY'S OWN
  responsibilities, achievements or technologies. Evidence owned by a different position
  belongs under that position — never move it, and never fuse facts from two employers into
  one bullet. This governs work-entry bullets only; the summary and skills list legitimately
  draw on the whole profile.
- Claim-strength: mirror the source's verb strength; never upgrade "supported"/"assisted" to
  "led"/"owned", never enlarge team sizes/budgets/magnitudes, never assign a more senior title.
  A figure keeps its own subject (#375): carry the thing the source says the number is a quantity
  OF, not only the number — "14 Jahren Erfahrung in der diskreten Fertigung" written as "14 Jahren
  Führungserfahrung" is an overstatement even though "14" is right, and the number staying
  defensible is exactly what stops any other check catching it.
  Claim only as much agency as the source statement itself gives the candidate (#289): an
  ORGANISATION-SCALE figure — the employer's or unit's revenue, headcount, portfolio, user base,
  as opposed to a result the candidate's own work produced — is the setting the work happened in.
  State the relationship the source states, or name it as the scale of the operation; never fuse
  it to the candidate's own action verb and leave the causation to the reader. Framing only:
  never drop the figure, a line vaguer than the truth is the opposite defect.
- Output language: write ALL prose in the OUTPUT LANGUAGE stated in the user message,
  translating from the source where needed (translating is not inventing). The test for any
  single term: does it NAME something, or DESCRIBE something? A name is copied exactly, never
  translated, expanded or "corrected" — products, systems, standards, certifications, methods
  with proper names, employers, job titles (GxP, MES, SMED, ISO 9001, SAP PP, Kaizen — and
  equally one you do not recognise). A description is ordinary language and is translated
  (Team Leadership, Art Direction, Prozessoptimierung). Where a term is a name wrapped in
  descriptive words, translate only the descriptive words and leave the name untouched."""


# ---------------------------------------------------------------------------
# Outline — the shared tailoring directive (small)
# ---------------------------------------------------------------------------

OUTLINE_SYSTEM_PROMPT = f"""\
You are a DACH cv outline planner. Given a job and a candidate profile, produce a SHORT
tailoring directive that later section writers will all follow — so the finished CV reads
with one consistent voice. Decide the summary angle, which skills to foreground, and a
one-line emphasis theme per work entry. Do NOT write the CV itself here.

When a ROLE BULLET BUDGETS block is present (E042/US237, ADR-051 §3), let each role's
bullet-count ceiling inform its emphasis theme — a role budgeted for a single line gets a
theme that reads as one condensed highlight, not a multi-point outline.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{
  "role_order": [string],          // work-entry ids, most-relevant-first (advisory only)
  "summary_angle": string,          // the angle the summary should take
  "skills_focus": [string],         // skills to lead with, drawn from the profile
  "per_role_themes": {{string: string}}  // work-entry id -> one-line emphasis theme
}}"""


def build_outline_prompt(
    job_analysis: dict,
    profile: dict,
    output_language: str,
    keyword_ledger: list[dict] | None = None,
    budget: "BudgetResult | None" = None,
) -> str:
    from applire.services.cv_budget import render_budget_table

    budget_block = render_budget_table(budget) if budget is not None else ""
    budget_section = f"{budget_block}\n\n" if budget_block else ""
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        f"{budget_section}"
        "Return the tailoring directive JSON."
    )


# ---------------------------------------------------------------------------
# Per-work-entry section — tailored bullets + nested projects only
# ---------------------------------------------------------------------------

WORK_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv work experience writer. Rewrite the bullets for ONE work-history entry to
maximise relevance to the job, following the shared tailoring directive. You return ONLY the
tailored bullets and any nested projects — never the company, role, or dates (those are
carried verbatim from the profile by the system).

When a MAX BULLETS FOR THIS ENTRY constraint is present (E042/US237, ADR-051 §3), treat it as
a hard ceiling on the number of bullets you return, not a quota to fill: select the most
JD-relevant achievements first, and condense a low-budget entry toward a single strong line
rather than padding it out.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{
  "bullets": [string],
  "projects": [{{"name": string, "bullets": [string]}}]
}}"""


def build_work_section_prompt(
    entry: dict,
    directive: dict,
    job_analysis: dict,
    keyword_gaps: list[str],
    output_language: str,
    keyword_ledger: list[dict] | None = None,
    budget: "BudgetResult | None" = None,
    scope_positioning_block: str | None = None,
    vault_evidence_block: str | None = None,
    pinned_facts_block: str | None = None,
) -> str:
    """One work entry's tailoring prompt (segmented path).

    ``vault_evidence_block`` (#303) must already be OWNER-SCOPED to this entry
    (:func:`applire.services.vault_evidence.filter_vault_evidence_for_owner`);
    a whole-vault digest here would offer this writer another employer's
    achievement, which is exactly the ADR-071 misattribution class. Optional;
    omitted/empty leaves the prompt byte-identical.
    """
    from applire.services.cv_budget import role_budget_line

    theme = (directive.get("per_role_themes") or {}).get(entry.get("id"), "")
    budget_line = role_budget_line(budget, entry.get("id", "")) if budget is not None else ""
    budget_section = f"{budget_line}\n" if budget_line else ""
    # ADR-070 clause 2 (segmented-path parity, ADR-066): the same scope-positioning
    # block the single-call writer receives — the attested bullet belongs in ITS
    # matching role, and only the writer of that entry can place it.
    scope_section = f"{scope_positioning_block}\n\n" if scope_positioning_block else ""
    evidence_section = f"{vault_evidence_block}\n\n" if vault_evidence_block else ""
    # ADR-077 clause 3 (segmented-path parity, ADR-066): the same PINNED FACTS
    # block the single-call writer receives — a pinned bullet belongs in ITS
    # matching role, and only the writer of that entry can weave it.
    pinned_section = f"{pinned_facts_block}\n\n" if pinned_facts_block else ""
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"EMPHASIS THEME FOR THIS ENTRY: {theme or '(use the summary angle)'}\n"
        f"SUMMARY ANGLE: {directive.get('summary_angle', '')}\n"
        f"{budget_section}\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"THIS WORK ENTRY:\n{json.dumps(entry, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        f"{evidence_section}"
        f"{scope_section}"
        f"{pinned_section}"
        f"KEYWORD GAPS (use only where explicitly supported by this entry):\n"
        f"{json.dumps(keyword_gaps, ensure_ascii=False)}\n\n"
        "Return the tailored bullets + nested projects JSON for this entry only."
    )


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

SUMMARY_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv summary writer. Write a concise professional summary (2–3 sentences, third
person) tailored to the job, taking the angle from the shared directive.

When a KEYWORD LEDGER block is present below, LEAD the summary with the JD's top CLAIMABLE
concepts (the terms the profile evidence backs) — the summary is the first thing a reviewer
reads and must truthfully aim at THIS job. Do not let an earlier, no-longer-central specialism
dominate the summary when the ledger shows stronger, more current support elsewhere (#235 —
a summary for a role the ledger backs must not read as still positioned for the candidate's
previous career).

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown: {{"summary": string}}"""


def build_summary_prompt(
    directive: dict,
    job_analysis: dict,
    profile: dict,
    output_language: str,
    keyword_ledger: list[dict] | None = None,
    stated_limits_block: str | None = None,
    pinned_facts_block: str | None = None,
) -> str:
    """stated_limits_block: the candidate's persisted denial statements rendered
    verbatim (mirrors cv_tailoring.build_user_prompt's kwarg of the same name), so no
    section contradicts one — and none invents one either. Optional; empty → adds
    nothing (back-compat).

    E049 (#383 prompt-side half): the former CRITICAL GAPS block is gone — it
    unconditionally instructed the summary to "acknowledge" the very gaps the shared
    rules forbid disclosing on a CV. Gap handling is the Keyword Ledger's job."""
    stated_limits_section = f"{stated_limits_block}\n\n" if stated_limits_block else ""
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"SUMMARY ANGLE: {directive.get('summary_angle', '')}\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        f"{stated_limits_section}"
        "Return the summary JSON."
    )


# ---------------------------------------------------------------------------
# Skills
# ---------------------------------------------------------------------------

# 2026-08-31 (ADR-062, applire-prompt-first): the "one entry per competence" paragraph
# below mirrors cv_tailoring.SYSTEM_PROMPT's rule 7 sub-rule of the same name — see that
# file's v12 changelog entry for the full rationale (the four observed shapes, why the
# survivor is the vault's own term/the NAME side and never the job ad's wording, and the
# known residual risk from #376's _restore_narrative_named_skills). Two independent
# builders emit `skills`; a rule written into only one is no rule at the other.
SKILLS_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv skills writer. Filter and order the candidate's skills to lead with those
the job requires, following the directive's skills focus. Include a keyword-gap skill ONLY if
the profile explicitly demonstrates it. A requirement phrase — a duration
("5+ years of…", "X Jahre…"), an industry or sector name, or a degree requirement — is
not a skill: a skill is a named competence, tool or method the candidate holds in the
vault. An industry or sector name ("Maschinenbau", "Verpackungsindustrie") and years of
experience are the SETTING of the work — they belong in the summary or in the bullet that
states them, never in the skills list.

One entry per competence, even with no shared token: an acronym beside its expansion or
description (MES / Maschinen- und Betriebsdatenerfassung), close synonyms (Lean Management /
Lean Production), a compound sharing another entry's stem (Budgetverantwortung /
Budgetplanung), or a norm beside the discipline it belongs to (ISO 45001 /
Arbeitssicherheitsmanagement) — keep both ONLY with separate evidence for each, and never
across codes, modules or standards themselves: SAP PP stays apart from SAP MM, ISO 9001 stays
apart from ISO 45001. When they do collapse, the NAME wins over the description (an acronym,
product, standard or method name beats a form that only describes it); otherwise keep the
profile's own term, never the job ad's wording where the two differ, and never a phrasing you
invent.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown: {{"skills": [string]}}"""


def build_skills_prompt(
    directive: dict,
    job_analysis: dict,
    profile: dict,
    keyword_gaps: list[str],
    output_language: str,
    keyword_ledger: list[dict] | None = None,
    stated_limits_block: str | None = None,
    pinned_facts_block: str | None = None,
) -> str:
    """stated_limits_block: the candidate's persisted denial statements rendered
    verbatim (mirrors cv_tailoring.build_user_prompt's kwarg of the same name), so
    the skills list never asserts something they explicitly disclaimed — and never
    hedges something they did not. Optional; empty → adds nothing (back-compat)."""
    stated_limits_section = f"{stated_limits_block}\n\n" if stated_limits_block else ""
    # ADR-077 clause 3: a pinned scalar fact (skill/certification/language)
    # surfaces through the skills writer — same block as the single-call path.
    pinned_section = f"{pinned_facts_block}\n\n" if pinned_facts_block else ""
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"SKILLS TO FOREGROUND: {json.dumps(directive.get('skills_focus') or [], ensure_ascii=False)}\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        f"{_ledger_section(keyword_ledger)}"
        f"{stated_limits_section}"
        f"{pinned_section}"
        f"KEYWORD GAPS (include only where explicitly demonstrated):\n"
        f"{json.dumps(keyword_gaps, ensure_ascii=False)}\n\n"
        "Return the skills JSON."
    )


# E049 / ADR-067 clause 3: the education + languages section LLM call is REMOVED.
# Education entries and spoken languages carry no authored content — they are
# transcription, copied wholesale from the vault at assembly (services/cv.
# assemble_tailored_cv), like certifications and contact. An LLM call whose only
# job was echoing facts was a defect on the same principle the single-call
# narrowing fixes.


# ---------------------------------------------------------------------------
# Standalone projects (those with no work/volunteer parent — US187)
# ---------------------------------------------------------------------------

PROJECTS_SECTION_SYSTEM_PROMPT = f"""\
You are a DACH cv projects writer. Return ONLY standalone projects (those not tied to a work
or volunteer position), tailored to the job. If the profile has none, return an empty list.

{_CORE_RULES}

Respond ONLY with a JSON object — no markdown:
{{"projects": [{{"name": string, "bullets": [string]}}]}}"""


def build_projects_prompt(
    directive: dict, job_analysis: dict, profile: dict, output_language: str
) -> str:
    return (
        f"OUTPUT LANGUAGE: {_language_name(output_language)}.\n\n"
        f"JOB ANALYSIS:\n{json.dumps(job_analysis, ensure_ascii=False, indent=2)}\n\n"
        f"CANDIDATE PROFILE:\n{json.dumps(profile, ensure_ascii=False, indent=2)}\n\n"
        "Return the standalone-projects JSON."
    )
