# Copyright (C) 2026 Tobias Rosenbaum
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Signed document links for the agent door (ADR-091 cl. 18, D-5; frozen interface F3).

``…/{html,pdf,docx}?exp=<unix>&uid=<user uuid>&sig=<b64url>`` with

    sig = HMAC-SHA256(derive_key("doc-link"), "<kind>:<doc_id>:<user_id>:<link_epoch>:<exp>")

* The key is **purpose-derived** from ``instance_state.auth.instance_secret``
  (ADR-091 cl. 10, D-8 — generated by the lifespan, package 1a), so a document-link
  MAC can never be replayed as an OIDC-state MAC (``derive_key("oidc-state")``).
* ``uid`` travels in the URL (CONTRACT-CHANGE 1c-2, accepted 2026-10-03) so the
  MAC, the ``link_epoch`` and the user's status are verified against ``users``
  alone **before** any owned table is read; the ownership check then runs under
  that user's owner context (ADR-092).
* ``users.link_epoch`` bumps on agent-token revoke, admin revoke-all, disable and
  delete, so outstanding links die with the token (adversarial-security §S).
* Lifetime ``AGENT_LINK_TTL_MINUTES`` (60, RD-8). REST URLs stay unsigned.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import time
import uuid
from typing import Literal
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from applire.models.user import User

#: ``cv`` → ``/api/cv/{id}/{html,pdf,docx}``; ``cover_letter`` → ``/api/cover-letter/{id}/…``.
DocumentKind = Literal["cv", "cover_letter"]
DOCUMENT_KINDS: tuple[DocumentKind, ...] = ("cv", "cover_letter")

#: The ``instance_state`` row holding the instance secret (written by 1a's lifespan;
#: read here by key string so this module does not depend on the KNOWN_KEYS list).
INSTANCE_SECRET_KEY = "auth.instance_secret"

#: Purposes ``derive_key`` serves. Closed: a new purpose is a code change.
KeyPurpose = Literal["doc-link", "oidc-state"]
KEY_PURPOSES: tuple[KeyPurpose, ...] = ("doc-link", "oidc-state")

DEFAULT_LINK_TTL_MINUTES = 60
LINK_QUERY_PARAMS = ("exp", "uid", "sig")

_instance_secret: bytes | None = None


class LinkExpired(Exception):
    """``exp`` in the past or non-numeric — the route answers 410 ``link_expired``."""


class InstanceSecretMissing(RuntimeError):
    """The instance secret has not been generated/loaded — no link can be signed."""


# ---------------------------------------------------------------------------
# The instance secret and purpose-derived keys
# ---------------------------------------------------------------------------


def _coerce_secret(value: object) -> bytes | None:
    if value is None:
        return None
    if isinstance(value, bytes):
        return value or None
    if isinstance(value, str):
        return value.encode("utf-8") or None
    # A JSON object/number would be a writer bug; refuse rather than guess.
    raise TypeError(f"instance secret has unexpected type {type(value).__name__}")


def set_instance_secret(value: str | bytes | None) -> None:
    """Install the process's copy of the instance secret (lifespan, MCP start, tests)."""
    global _instance_secret
    _instance_secret = _coerce_secret(value)


async def load_instance_secret(db: AsyncSession) -> bytes | None:
    """Read ``instance_state['auth.instance_secret']`` into the process cache.

    Returns ``None`` (and leaves the cache untouched) when the row is absent —
    an instance whose lifespan has not generated it yet signs nothing.
    """
    from applire.models.instance_state import InstanceState

    try:
        value = (
            await db.execute(
                select(InstanceState.value).where(InstanceState.key == INSTANCE_SECRET_KEY)
            )
        ).scalar_one_or_none()
    except Exception:  # pre-0062 instance: no table
        await db.rollback()
        return None
    secret = _coerce_secret(value)
    if secret is not None:
        set_instance_secret(secret)
    return secret


def derive_key(purpose: KeyPurpose) -> bytes:
    """``HMAC-SHA256(instance_secret, "applire/<purpose>")`` — one key per purpose.

    Raises ``InstanceSecretMissing`` when the secret is not loaded.
    """
    if purpose not in KEY_PURPOSES:
        raise ValueError(f"unknown key purpose {purpose!r}")
    if _instance_secret is None:
        raise InstanceSecretMissing(
            "instance secret not loaded — call load_instance_secret(db) at start"
        )
    return hmac.new(_instance_secret, f"applire/{purpose}".encode(), hashlib.sha256).digest()


# ---------------------------------------------------------------------------
# Signing
# ---------------------------------------------------------------------------


def _configured_ttl_minutes() -> object:
    """``AGENT_LINK_TTL_MINUTES`` (registry entry + ``Settings`` field by 1a)."""
    from applire.config import settings

    return getattr(settings, "agent_link_ttl_minutes", DEFAULT_LINK_TTL_MINUTES)


def link_ttl_seconds() -> int:
    minutes = _configured_ttl_minutes()
    try:
        minutes = int(minutes)
    except (TypeError, ValueError):
        minutes = DEFAULT_LINK_TTL_MINUTES
    return max(1, minutes) * 60


def _mac(kind: str, doc_id: uuid.UUID | str, user_id: uuid.UUID | str, epoch: int, exp: str) -> str:
    message = f"{kind}:{doc_id}:{user_id}:{int(epoch)}:{exp}".encode()
    digest = hmac.new(derive_key("doc-link"), message, hashlib.sha256).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def sign_document_url(
    kind: DocumentKind,
    doc_id: uuid.UUID,
    user: User,
    base: str,
    *,
    now: float | None = None,
) -> str:
    """Append ``exp``/``uid``/``sig`` to the absolute document URL ``base`` for ``user``.

    ``base`` is the unsigned URL the door would otherwise return (it may already
    carry a query string; any earlier ``exp``/``uid``/``sig`` are replaced, so a
    re-sign of a ``get_cv_status`` URL is idempotent in shape). Pure function of
    the instance secret, the user's ``link_epoch`` and the clock.
    """
    if kind not in DOCUMENT_KINDS:
        raise ValueError(f"unknown document kind {kind!r}")
    exp = str(int(now if now is not None else time.time()) + link_ttl_seconds())
    sig = _mac(kind, doc_id, user.id, getattr(user, "link_epoch", 0) or 0, exp)
    parts = urlsplit(base)
    query = [(k, v) for k, v in parse_qsl(parts.query, keep_blank_values=True) if k not in LINK_QUERY_PARAMS]
    query += [("exp", exp), ("uid", str(user.id)), ("sig", sig)]
    return urlunsplit(parts._replace(query=urlencode(query)))


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def check_exp(exp: str | None, *, now: float | None = None) -> int:
    """The numeric expiry, or ``LinkExpired`` for a past/non-numeric/absent ``exp``."""
    if not exp or not exp.isascii() or not exp.isdigit() or len(exp) > 12:
        raise LinkExpired("non-numeric exp")
    value = int(exp)
    if value <= int(now if now is not None else time.time()):
        raise LinkExpired("link expired")
    return value


async def verify_document_link(
    kind: DocumentKind,
    doc_id: uuid.UUID,
    exp: str,
    sig: str,
    db: AsyncSession,
    uid: str | uuid.UUID | None = None,
    *,
    now: float | None = None,
) -> User | None:
    """The user a valid link was signed for, if that user is active and still owns
    the document; ``None`` for a bad signature, a stale epoch, an inactive user or
    a foreign/missing document; raises ``LinkExpired`` for a past or non-numeric
    ``exp`` (410).

    Order: ``exp`` → MAC (``compare_digest``) over the user's **current**
    ``link_epoch`` → user active → ownership under ``owner_context(uid)``. No owned
    table is read before the MAC holds.
    """
    from applire.auth.tokens import user_is_active

    if kind not in DOCUMENT_KINDS:
        return None
    check_exp(exp, now=now)
    try:
        user_id = uuid.UUID(str(uid))
    except (TypeError, ValueError):
        return None
    if not sig or not isinstance(sig, str):
        return None
    if _instance_secret is None and await load_instance_secret(db) is None:
        return None
    user = await db.get(User, user_id, populate_existing=True)
    if user is None:
        return None
    expected = _mac(kind, doc_id, user.id, getattr(user, "link_epoch", 0) or 0, exp)
    if not hmac.compare_digest(expected.encode("ascii"), sig.encode("ascii", "replace")):
        return None
    if not user_is_active(user):
        return None
    if not await _owns_document(db, kind, doc_id, user.id):
        return None
    return user


async def _owns_document(
    db: AsyncSession, kind: DocumentKind, doc_id: uuid.UUID, user_id: uuid.UUID
) -> bool:
    """Ownership check under the signer's owner context (ADR-092 ``get_owned``)."""
    from applire.models.cover_letter import GeneratedCoverLetter
    from applire.models.cv import GeneratedCV
    from applire.ownership import OwnedNotFound, get_owned, owner_context

    model = GeneratedCV if kind == "cv" else GeneratedCoverLetter
    with owner_context(user_id):
        if not hasattr(model, "user_id"):
            # Integration shim (removed by the main session once 3a's 0075 owner
            # column is merged): before the column exists there is one user, so
            # existence is ownership.
            return await db.get(model, doc_id) is not None
        try:
            await get_owned(db, model, doc_id, user_id)
        except OwnedNotFound:
            return False
    return True
