# Copyright (C) 2024-2026 Tobias Rosenbaum
#
# This file is part of Applire.
#
# Applire is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Applire is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Applire. If not, see <https://www.gnu.org/licenses/>.

"""Unit tests for the shared ExperienceBase abstraction (US172 / ADR-044).

Covers ProjectEntry (new), the volunteer date-type refinement, the
MasterProfileData.projects field + all_experiences accessor, and the
Skill.work_entry_refs → experience_refs rename with legacy load.
"""


class TestExperienceBaseSubclasses:
    def test_workentry_unchanged_org_label_is_company(self):
        from applire.schemas.profile import WorkEntry

        we = WorkEntry(
            company="Siemens AG",
            role="Engineer",
            start_date="2020-01",
            end_date="2021-01",
            responsibilities=["did stuff"],
            achievements=["shipped X"],
            technologies=["Python"],
        )
        assert we.company == "Siemens AG"
        assert we.org_label() == "Siemens AG"
        assert we.achievements == ["shipped X"]
        assert we.technologies == ["Python"]
        # id is still autogenerated
        assert isinstance(we.id, str) and we.id

    def test_volunteer_gains_capabilities_and_str_dates(self):
        from applire.schemas.profile import VolunteerActivity

        va = VolunteerActivity(
            role="x",
            organization="NGO",
            achievements=["shipped X"],
            technologies=["Python"],
            start_date="2019",
        )
        assert va.org_label() == "NGO"
        assert va.achievements == ["shipped X"]
        assert va.technologies == ["Python"]
        assert va.start_date == "2019"
        # round-trips through JSON
        dumped = va.model_dump(mode="json")
        restored = VolunteerActivity.model_validate(dumped)
        assert restored == va

    def test_project_entry_basics(self):
        from applire.schemas.profile import ProjectEntry

        p = ProjectEntry(name="P", achievements=["did Y"], technologies=["Go"])
        assert p.org_label() == "P"
        assert p.achievements == ["did Y"]
        assert p.technologies == ["Go"]
        assert isinstance(p.id, str) and p.id
        assert p.associated_experience is None


class TestMasterProfileProjects:
    def test_legacy_profile_without_projects_loads_empty(self):
        from applire.schemas.profile import MasterProfileData

        legacy = {
            "work_experience": [{"company": "C", "role": "R"}],
            "skills": [{"name": "Python"}],
        }
        profile = MasterProfileData(**legacy)
        assert profile.projects == []

    def test_all_experiences_aggregates_in_order(self):
        from applire.schemas.profile import (
            MasterProfileData,
            ProjectEntry,
            VolunteerActivity,
            WorkEntry,
        )

        profile = MasterProfileData(
            work_experience=[WorkEntry(company="C", role="R")],
            projects=[ProjectEntry(name="P")],
            volunteer_activities=[VolunteerActivity(role="x", organization="NGO")],
        )
        labels = [e.org_label() for e in profile.all_experiences]
        assert labels == ["C", "P", "NGO"]


class TestSkillExperienceRefs:
    def test_construct_with_new_kwarg(self):
        from applire.schemas.profile import Skill

        skill = Skill(name="Python", experience_refs=["C1", "C2"])
        assert skill.experience_refs == ["C1", "C2"]

    def test_legacy_work_entry_refs_loads_into_experience_refs(self):
        from applire.schemas.profile import Skill

        skill = Skill.model_validate(
            {"name": "Python", "work_entry_refs": ["Siemens AG"]}
        )
        assert skill.experience_refs == ["Siemens AG"]

    def test_experience_refs_defaults_empty(self):
        from applire.schemas.profile import Skill

        assert Skill(name="Python").experience_refs == []

    def test_experience_refs_coerces_null(self):
        from applire.schemas.profile import Skill

        assert Skill(name="Python", experience_refs=None).experience_refs == []
