# Copyright (C) 2026 Tobias Rosenbaum
# SPDX-License-Identifier: AGPL-3.0-or-later

"""US248 — MCP `audit_document` (ADR-054 à-la-carte, ADR-052 flagship).

The tool must work with NO prior generate_* call (external text mode) and
return/persist the report for stored documents. The seeded trap document
reproduces the 2026-07-18 bug class #1 (target→achieved inflation — flagged);
bug class #2 (cross-role misattribution, shipped 2026-07-19 / #196) is
structurally out of reach on THIS door: raw `document_text` carries no
rendered-position ids, so the attribution matcher stays silent by design
(asserted below as the documented raw-text limit; the stored-document path is
covered in backend/tests/unit/services/test_oracle_misattribution.py).
"""
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
import pytest_asyncio
from mcp.shared.exceptions import McpError
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

_backend = Path(__file__).parent.parent.parent / "backend"
if str(_backend) not in sys.path:
    sys.path.insert(0, str(_backend))


PROFILE_JSON = {
    "professional_summary": {"en": "IT leader focused on compliance automation."},
    "work_experience": [
        {
            "company": "Acme GmbH",
            "role": "Head of IT",
            "start_date": "2019-03",
            "end_date": "2023-05",
            "responsibilities": ["Led a team of 12 engineers."],
            "achievements": [
                # bug class #1 source: an ASPIRATIONAL target in the vault
                "Rollout of a compliance workflow that targets a ~70% reduction "
                "in manual effort.",
            ],
            "technologies": ["Python", "Kubernetes"],
        },
        {
            "company": "Beta AG",
            "role": "IT Consultant",
            "start_date": "2015-01",
            "end_date": "2019-02",
            "achievements": [
                # bug class #2 source: this programme belongs to Beta AG
                "Prepared the FDA audit readiness programme."
            ],
        },
    ],
    "skills": [{"name": "Python"}, {"name": "Kubernetes"}],
}

# The trap document (agent-authored, never generated by Applire):
TRAP_DOCUMENT = (
    "Head of IT, Acme GmbH (2019 - 2023)\n"
    "- Reduced manual effort by 70% via a compliance workflow\n"
    "- Prepared the FDA audit readiness programme\n"
    "- Led a team of 12 engineers\n"
)


@pytest_asyncio.fixture
async def db():
    from applire.db.session import Base  # noqa: F401
    import applire.models.user  # noqa: F401
    import applire.models.job  # noqa: F401
    import applire.models.profile  # noqa: F401
    import applire.models.gap  # noqa: F401
    import applire.models.cv  # noqa: F401
    import applire.models.cover_letter  # noqa: F401
    import applire.models.session  # noqa: F401
    import applire.models.flow  # noqa: F401
    import applire.models.uploads  # noqa: F401
    import applire.models.application  # noqa: F401
    import applire.models.color_profile  # noqa: F401
    import applire.models.company  # noqa: F401
    import applire.models.user_settings  # noqa: F401

    engine = create_async_engine("sqlite+aiosqlite:///:memory:", echo=False)
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    factory = async_sessionmaker(engine, expire_on_commit=False)
    async with factory() as session:
        yield session
    await engine.dispose()


def _db_cm(session):
    cm = MagicMock()
    cm.__aenter__ = AsyncMock(return_value=session)
    cm.__aexit__ = AsyncMock(return_value=False)
    return cm


@pytest_asyncio.fixture
async def seeded(db):
    from applire.models.cv import GeneratedCV
    from applire.models.job import JobAnalysis
    from applire.models.profile import MasterProfile

    job_id, profile_id, cv_id = uuid.uuid4(), uuid.uuid4(), uuid.uuid4()
    db.add_all(
        [
            JobAnalysis(
                id=job_id,
                raw_text_hash="mcp-oracle",
                raw_text="Head of IT job",
                role_title="Head of IT",
                required_skills=["Python"],
                nice_to_have_skills=[],
                keywords=["Python"],
                seniority_level="senior",
                company_culture_signals=[],
                language_requirement="en",
            ),
            MasterProfile(
                id=profile_id,
                profile_json=PROFILE_JSON,
                created_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
                updated_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
            ),
            GeneratedCV(
                id=cv_id,
                job_analysis_id=job_id,
                profile_id=profile_id,
                tailored_data={
                    "contact": {"name": "Anna Bauer"},
                    "summary": "Reduced manual effort by 70%.",
                    "work_history": [],
                    "skills": ["Python"],
                },
                template="classic_german",
                status="ready",
                truthfulness_report=None,
                created_at=datetime(2026, 1, 1, tzinfo=timezone.utc),
                expires_at=datetime(2027, 1, 1, tzinfo=timezone.utc),
            ),
        ]
    )
    await db.commit()
    return {"db": db, "cv_id": cv_id, "profile_id": profile_id}


@pytest.mark.asyncio
async def test_requires_exactly_one_input():
    from applire.mcp.server import audit_document

    for kwargs in ({}, {"document_id": str(uuid.uuid4()), "document_text": "x"}):
        with pytest.raises(McpError) as exc_info:
            await audit_document(**kwargs)
        assert exc_info.value.error.code == -32602


@pytest.mark.asyncio
async def test_external_text_no_prior_generate_call(seeded):
    """ADR-054 à la carte: raw agent-authored text audits against the vault —
    the trap document's inflation (bug class #1) is flagged deterministically."""
    from applire.mcp.server import audit_document

    with (
        patch("applire.mcp.server.get_db", return_value=_db_cm(seeded["db"])),
        patch("applire.mcp.server.get_provider", return_value=None),
    ):
        report = await audit_document(document_text=TRAP_DOCUMENT)

    assert report["document_kind"] == "external"
    assert report["stated_limit"]
    by_text = {c["claim"]["text"]: c["verdict"] for c in report["claims"]}
    inflated = by_text["Reduced manual effort by 70% via a compliance workflow"]
    assert inflated["verdict"] == "inflated"
    assert inflated["checker"] == "stance"
    # the honest bullet stays green
    assert by_text["Led a team of 12 engineers"]["verdict"] == "grounded"
    # bug class #2 (misattribution, #196): the verdict EXISTS since 2026-07-19
    # but cannot fire on raw text — extract_claims_from_text has no rendered-
    # position ids to stamp, so the matcher is silent on this door (documented
    # in the tool description). Stored generated documents ARE covered.
    fda = by_text["Prepared the FDA audit readiness programme"]
    assert fda["verdict"] in ("grounded", "unverifiable")


@pytest.mark.asyncio
async def test_external_text_without_profile_raises_not_found(db):
    from applire.mcp.server import audit_document

    with (
        patch("applire.mcp.server.get_db", return_value=_db_cm(db)),
        patch("applire.mcp.server.get_provider", return_value=None),
    ):
        with pytest.raises(McpError) as exc_info:
            await audit_document(document_text="- Reduced costs by 30%")
    assert exc_info.value.error.code == -32001


@pytest.mark.asyncio
async def test_stored_cv_computes_and_persists(seeded):
    from applire.mcp.server import audit_document
    from applire.models.cv import GeneratedCV

    with (
        patch("applire.mcp.server.get_db", return_value=_db_cm(seeded["db"])),
        patch("applire.mcp.server.get_provider", return_value=None),
    ):
        report = await audit_document(document_id=str(seeded["cv_id"]))

    assert report["document_id"] == str(seeded["cv_id"])
    assert report["document_kind"] == "cv"
    by_loc = {c["claim"]["location"]: c["verdict"]["verdict"] for c in report["claims"]}
    assert by_loc["summary[0]"] == "inflated"

    # persisted for the UI panel (backfills a pre-Tiramisu/NULL row)
    record = await seeded["db"].get(GeneratedCV, seeded["cv_id"])
    assert record.truthfulness_report is not None


@pytest.mark.asyncio
async def test_stored_cv_returns_persisted_report_without_recompute(seeded):
    from applire.mcp.server import audit_document
    from applire.models.cv import GeneratedCV

    session = seeded["db"]
    record = await session.get(GeneratedCV, seeded["cv_id"])
    sentinel = {"version": "1.0", "document_kind": "cv", "claims": [],
                "counts": {}, "stated_limit": "x",
                "generated_at": "2026-07-18T00:00:00Z"}
    record.truthfulness_report = sentinel
    await session.commit()

    with (
        patch("applire.mcp.server.get_db", return_value=_db_cm(session)),
        patch("applire.mcp.server.get_provider", return_value=None),
    ):
        report = await audit_document(document_id=str(seeded["cv_id"]))

    assert report["stated_limit"] == "x"  # the stored report, not a recompute


@pytest.mark.asyncio
async def test_unknown_document_id_raises_not_found(seeded):
    from applire.mcp.server import audit_document

    with (
        patch("applire.mcp.server.get_db", return_value=_db_cm(seeded["db"])),
        patch("applire.mcp.server.get_provider", return_value=None),
    ):
        with pytest.raises(McpError) as exc_info:
            await audit_document(document_id=str(uuid.uuid4()))
    assert exc_info.value.error.code == -32001
