# Copyright (C) 2026 Tobias Rosenbaum
# SPDX-License-Identifier: AGPL-3.0-or-later
"""ADR-090 clause 2 — one shared vector file pins the audit's `_norm` to the
frontend's TypeScript port (`lib/locate-in-preview.ts`, WP-C).

`tests/files/ats_norm_vectors.json` is GENERATED from the Python `_norm`
(`python3 tests/unit/test_ats_norm_vectors.py --write`, with PYTHONPATH=backend
and the hermetic env). This test re-derives every expected value from the live
Python function, so a change to `_norm` that is not regenerated fails here, and
the regenerated file then fails the TypeScript test until the port follows.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

VECTORS = Path(__file__).resolve().parents[1] / "files" / "ats_norm_vectors.json"

# Inputs chosen to exercise every step of `_norm`, plus the characters a
# rendered preview carries that the PDF text layer may not.
INPUTS: list[str] = [
    "IT Data & AI Governance",
    "AI governance",
    "Code-Review",
    "code review",
    "Lean‑Produktion",  # non-breaking hyphen
    "Lean–Produktion",  # en dash
    "Lean—Produktion",  # em dash
    "Lean−Produktion",  # minus sign
    "Lean‐Produktion",  # hyphen
    "Ver­packungen",  # soft hyphen
    "  leading and   trailing\twhitespace\n",
    "non breaking space",
    "narrow no-break",
    "ﬁnance ﬂow",  # ligatures fi / fl (NFKC)
    "ＡＩ Governance",  # fullwidth AI (NFKC)
    "Straße Mitarbeiterführung",  # ß stays ß under lower()
    "MITARBEITERFÜHRUNG",
    "Führung",  # decomposed ü (NFKC composes)
    "ISO-45001",
    "ISO 9001␞ISO 14001",  # corpus fragment boundary survives
    "C# / .NET",
    "CI/CD",
    "SAP PP/MM",
    "café Ωhm",  # Ohm sign → Ω (NFKC) → ω
    "½ Stelle",  # vulgar fraction (NFKC → 1⁄2)
    "Event-driven   architecture",
    "",
]


def _norm():
    from applire.services.ats_audit import _norm as n

    return n


def build_vectors() -> list[dict[str, str]]:
    n = _norm()
    return [{"input": s, "expected": n(s)} for s in INPUTS]


def test_vector_file_matches_python_norm():
    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    n = _norm()
    assert data["source"] == "applire.services.ats_audit._norm"
    assert len(data["vectors"]) >= 20
    for v in data["vectors"]:
        assert n(v["input"]) == v["expected"], v


def test_vector_file_is_current_with_the_generator():
    data = json.loads(VECTORS.read_text(encoding="utf-8"))
    assert data["vectors"] == build_vectors(), (
        "regenerate tests/files/ats_norm_vectors.json with --write"
    )


if __name__ == "__main__" and "--write" in sys.argv:
    VECTORS.write_text(
        json.dumps(
            {
                "source": "applire.services.ats_audit._norm",
                "adr": "ADR-090 clause 2",
                "note": "Generated by tests/unit/test_ats_norm_vectors.py --write; read by the Python and the TypeScript test.",
                "vectors": build_vectors(),
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {VECTORS}")
